services:
  localstack:
    image: localstack/localstack:0.14.3
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=dynamodb
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - KINESIS_PROVIDER=kinesalite
    ports:
      - '4566:4566'
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  webhook-mock:
    image: mockoon/cli
    platform: linux/x86_64
    hostname: webhook-mock
    ports:
      - '9999:9999'
    command: -d /data -p 9999
    volumes:
      - ./src/main/resources/mockoon/webhook-mock.json:/data
    networks:
      - backend-postgres
volumes:
  data:
    external: true
networks:
  backend-postgres: